# Generated by Django 4.1 on 2023-04-01 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("subtitulo", models.CharField(max_length=255)),
                ("cuerpo", models.TextField()),
                ("autor", models.CharField(max_length=20)),
                ("fecha", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Blogimg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="img_post")),
                (
                    "blog",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="App_prosopiki_filosofia.blog",
                    ),
                ),
            ],
        ),
    ]
