# Generated by Django 4.1 on 2023-03-30 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App_prosopiki_filosofia", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Post", new_name="Blog",),
    ]
