# Generated by Django 4.1 on 2023-04-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_prosopiki_filosofia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog", name="autor", field=models.CharField(max_length=50),
        ),
    ]
