# Generated by Django 4.1 on 2023-04-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_prosopiki_filosofia", "0002_alter_blogimg_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogimg",
            name="imagen",
            field=models.ImageField(upload_to="img_post"),
        ),
    ]
