# Generated by Django 4.1 on 2023-03-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_prosopiki_filosofia", "0002_rename_post_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog", name="subtitulo", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="blog", name="titulo", field=models.CharField(max_length=255),
        ),
    ]
