# Generated by Django 4.1 on 2023-04-01 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("App_prosopiki_filosofia", "0003_alter_blogimg_imagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blogcomments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="App_prosopiki_filosofia.blog",
                    ),
                ),
            ],
        ),
    ]
