# Generated by Django 4.1 on 2023-03-31 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("App_prosopiki_filosofia", "0003_alter_blog_subtitulo_alter_blog_titulo"),
    ]

    operations = [
        migrations.RemoveField(model_name="blog", name="imagen",),
        migrations.AlterField(
            model_name="blog", name="fecha", field=models.DateField(),
        ),
        migrations.CreateModel(
            name="Blog_img",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="img_post")),
                (
                    "Blog_img",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="App_prosopiki_filosofia.blog",
                    ),
                ),
            ],
        ),
    ]
