# Generated by Django 4.1 on 2023-04-01 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App_prosopiki_filosofia", "0004_blogcomments"),
    ]

    operations = [
        migrations.RenameModel(old_name="Blogcomments", new_name="Blogcomment",),
    ]
