# Generated by Django 4.1 on 2023-03-31 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App_prosopiki_filosofia", "0004_alter_blog_fecha"),
        (
            "App_prosopiki_filosofia",
            "0004_remove_blog_imagen_alter_blog_fecha_blog_img",
        ),
    ]

    operations = []
