# Generated by Django 4.1 on 2023-04-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_prosopiki_filosofia", "0005_rename_blogcomments_blogcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcomment",
            name="visto",
            field=models.BooleanField(default=False),
        ),
    ]
