# Generated by Django 4.1 on 2023-03-31 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App_prosopiki_filosofia", "0005_merge_20230331_1747"),
    ]

    operations = [
        migrations.RenameModel(old_name="Blog_img", new_name="Blogimg",),
        migrations.RenameField(
            model_name="blogimg", old_name="Blog_img", new_name="blog_id",
        ),
    ]
